### User route - Register a new user
POST http://localhost:3030/auth/register
Content-Type: application/json

{
  "firstname": "test2",
  "lastname": "test2",
  "email": "test2@example.com",
  "phone": "0811111111",
  "username": "test2",
  "password": "SecurePassword@123"

}

### User route - Register a new user
POST http://localhost:3030/orders
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGMyZjRmZjhmYTRjNDE1NzJjNGFhNTkiLCJpYXQiOjE3NTc4NDExMzMsImV4cCI6MTc1Nzg0NDczM30.-rzDBzNLO11OCh-c7XN7cnf3t-IU9p7Kud0eD-CLxg0

{
  "orderNumber": "ORD-20250914-001",
  "customerInfo": {
    "firstName": "John",
    "lastName": "Doe",
    "phoneNumber": "0812345678",
    "email": "john.doe@example.com"
  },
  "basketItems": [
    {
      "productId": "66ef1234abc4567890d12345",
      "name": "Hot Cappuccino",
      "price": 95,
      "quantity": 2
    },
    {
      "productId": "66ef6789abc4567890d67890",
      "name": "Hot Mocha",
      "price": 105,
      "quantity": 1
    }
  ],
  "orderType": "delivery",
  "address": "123 Coffee Street, Bangkok",
  "subtotal": 225,
  "deliveryFee": 20,
  "total": 245,
  "note": "Please deliver before 10 AM",
  "status": "preparing",
  "user": "66e5f6a2c0d5a72b3c1e45f0"
}




### User route - Login
POST http://localhost:3030/auth/login
Content-Type: application/json

{
  "username": "test4",
  "password": "Sep@2025"
}

### User route - Get User Profile
GET http://localhost:3030/auth/profile
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzE1NTc5MmFjM2ZjNGIxNWQ2Zjc0YiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU3NTAwNzkzLCJleHAiOjE3NjAwOTI3OTN9.c6aRkzTMLLcOsYgYlqag5mHBdN3n93vM2McIbpLsCmg



### Test route - Verify the token (replace <TOKEN> with the token from the login response)
GET http://localhost:3030/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzE1NTc5MmFjM2ZjNGIxNWQ2Zjc0YiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU3NTAwNzkzLCJleHAiOjE3NjAwOTI3OTN9.c6aRkzTMLLcOsYgYlqag5mHBdN3n93vM2McIbpLsCmg



GET http://localhost:3030/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzE1NTc5MmFjM2ZjNGIxNWQ2Zjc0YiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU3NTAwNzkzLCJleHAiOjE3NjAwOTI3OTN9.c6aRkzTMLLcOsYgYlqag5mHBdN3n93vM2McIbpLsCmg
Content-Type: application/json



### User route - Logout user
POST http://localhost:3030/auth/logout


### Admin User Route - Get all users
GET http://localhost:3030/users


### POST Order
POST http://localhost:3030/

