### User route - Register a new user
POST http://localhost:3030/auth/register
Content-Type: application/json

{
  "firstname": "test2",
  "lastname": "test2",
  "email": "test2@example.com",
  "phone": "0811111111",
  "username": "test2",
  "password": "SecurePassword@123"
}


### User route - Login
POST http://localhost:3030/auth/login
Content-Type: application/json

{
  "username": "test4",
  "password": "Sep@2025"
}

### User route - Get User Profile
GET http://localhost:3030/auth/profile
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzE1NTc5MmFjM2ZjNGIxNWQ2Zjc0YiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU3NTAwNzkzLCJleHAiOjE3NjAwOTI3OTN9.c6aRkzTMLLcOsYgYlqag5mHBdN3n93vM2McIbpLsCmg



### Test route - Verify the token (replace <TOKEN> with the token from the login response)
GET http://localhost:3030/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzE1NTc5MmFjM2ZjNGIxNWQ2Zjc0YiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU3NTAwNzkzLCJleHAiOjE3NjAwOTI3OTN9.c6aRkzTMLLcOsYgYlqag5mHBdN3n93vM2McIbpLsCmg



GET http://localhost:3030/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzE1NTc5MmFjM2ZjNGIxNWQ2Zjc0YiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU3NTAwNzkzLCJleHAiOjE3NjAwOTI3OTN9.c6aRkzTMLLcOsYgYlqag5mHBdN3n93vM2McIbpLsCmg
Content-Type: application/json



### User route - Logout user
POST http://localhost:3030/auth/logout


### Admin User Route - Get all users
GET http://localhost:3030/users








### Test Order: User route - Login
POST http://localhost:3030/auth/login
Content-Type: application/json

{
  "username": "JSR",
  "password": "0bsidianSip"
}

### Order Route - Create Order
POST http://localhost:3030/orders
Content-Type: application/json
Cookie: accessToken=


{
  "orderNumber": "ORD-20250914-001",
  "customerInfo": {
    "firstName": "JS",
    "lastName": "SR",
    "phoneNumber": "0888888888",
    "email": "john.doe@example.com"
  },
  "basketItems": [
    {
      "productId": "68c556c77d3e4daf9c2c190e",
      "name": "Iced Mocha",
      "price": 1,
      "quantity": 2
    },
    {
      "productId": "68c556c77d3e4daf9c2c191d",
      "name": "hot-chai-latte",
      "price": 95,
      "quantity": 1
    }
  ],
  "orderType": "delivery",
  "address": "N/A",
  "subtotal": 325,
  "deliveryFee":40,
  "total": 325,
  "note": "Please deliver at 11 PM",
  "status": "preparing",
  "user": "68c38e0999adeeae60c8bf72"
}


### Order Route - GET → all orders ของ user
GET http://localhost:3030/orders
Cookie: accessToken=

### Order Route - GET Single Order
GET http://localhost:3030/orders/68c697f4abb648bf9521ada7
Authorization: Bearer 
